#!/bin/bash

echo "Provisoing Script Start!!" >> /tmp/provisioning.txt

#user
useradd hayakawa
echo "hayakawa:1qaz2wsx" | chpasswd
usermod -G wheel hayakawa


# === パスワードによる認証を禁止
# ssh disable password authentication
sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart sshd.service

# === 日本語ロケールへ変更
# Change to Japanese locale
yum -y groupinstall "Japanese Support"
sed -i.org -e "s/en_US.UTF-8/ja_JP.UTF-8/g" /etc/sysconfig/i18n

# === タイムゾーンを日本標準時へ変更
# Change to JST time zone
/bin/cp -p /usr/share/zoneinfo/Japan /etc/localtime
echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
echo 'UTC=false' >> /etc/sysconfig/clock

#rm -f /etc/localtime
#ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

#=== ＯＳファイアウォールの設定
# Configure Linux Firewall
# FireWall
systemctl enable firewalld.service
systemctl start firewalld.service
firewall-cmd --add-service=http --zone=public --permanent
firewall-cmd --add-service=https --zone=public --permanent
firewall-cmd --reload


#=== 基本ツールのインストール
# Install basic tools
## Utility
yum install -y \
    bash-completion \
    bind-utils \
    lsof \
    net-tools \
    screen \
    sos \
    sysstat

## Editor
yum install -y \
    vim-enhanced

## MariaDB
yum install -y mariadb mariadb-server mariadb-devel

## DevTools
yum -y groupinstall "Development Tools"

## for Redmine
yum -y install openssl-devel readline-devel zlib-devel curl-devel libyaml-devel libffi-devel
yum -y install ImageMagick ImageMagick-devel ipa-pgothic-fonts
yum -y install ruby ruby-devel rubygems


# MariaDB Settings
mv /etc/my.cnf /etc/my.cnf.org
curl -OL https://raw.githubusercontent.com/kazuhisya/SL-Redmine/master/conf/mariadb-my.cnf
mv mariadb-my.cnf /etc/my.cnf

# Service Enable and Start
systemctl enable mariadb.service
systemctl start mariadb.service

# Create MariaDB Password
PASS=`date +%s | sha256sum | base64 | head -c 32`
echo $PASS > /root/db_password.txt

# Create Redmine DB
/usr/bin/mysql -e "CREATE DATABASE redmine DEFAULT CHARACTER SET utf8;" -D mysql
/usr/bin/mysql -e "GRANT ALL PRIVILEGES ON redmine.* TO redmine@'%' IDENTIFIED BY '${PASS}';" -D mysql

# mysql_secure_installation
/usr/bin/mysqladmin drop test -f
/usr/bin/mysql -e "DELETE FROM mysql.user WHERE User = '';" -D mysql
/usr/bin/mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'::1' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysqladmin flush-privileges -p${PASS}

# Ruby Gems
echo "gem: --no-ri --no-rdoc --user-install" > /root/.gemrc
echo "export PATH=\"\$HOME/.gem/ruby/bin:\$PATH\"" >> /root/.bashrc
export PATH="$HOME/.gem/ruby/bin:$PATH"
gem install bundler

# Redmine Download
curl -OL http://www.redmine.org/releases/redmine-3.0.3.tar.gz
tar xvf redmine-3.0.3.tar.gz
mv redmine-3.0.3 /var/lib/redmine

# Redmine Settings
cat << EOF | tee /var/lib/redmine/config/database.yml > /dev/null
production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: root
  password: "$PASS"
  encoding: utf8
EOF

cp /var/lib/redmine/config/configuration.yml.example /var/lib/redmine/config/configuration.yml
sed -i -e 's/  rmagick_font_path:/  rmagick_font_path: \/usr\/share\/fonts\/ipa-pgothic\/ipagp.ttf/' /var/lib/redmine/config/configuration.yml

curl -OL https://raw.githubusercontent.com/kazuhisya/SL-Redmine/master/conf/redmine-config.ru
mv /var/lib/redmine/config.ru /tmp/config.ru
mv redmine-config.ru /var/lib/redmine/config.ru

# Redmine Install
cd /var/lib/redmine
echo "gem \"unicorn\"" > Gemfile.local
bundle install --without development test --path vendor/bundle
bundle exec rake generate_secret_token
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production REDMINE_LANG=ja bundle exec rake redmine:load_default_data

